StartupEvents.registry('block', event => {

    function kubejs_ore(name) {
        event.create(name + '_ore')
            .stoneSoundType()
            .tagBlock('minecraft:mineable/pickaxe')
            .tagBlock('minecraft:needs_iron_tool')
            .tagBoth('forge:ores/' + name)
            .requiresTool(true)
    }
    event.create('quartz_alloy_block').tagBlock('minecraft:mineable/pickaxe').noValidSpawns(true)
    event.create('blockium').tagBlock('uc:tools/blockium').stoneSoundType().noValidSpawns(true).noDrops()
    event.create('overgrown_wood_log').tagBlock('minecraft:mineable/axe').noValidSpawns(true)
    event.create('coil_tier_1').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/coil_tier_1').displayName('Copper Coil').noValidSpawns(true)
    event.create('coil_tier_2').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/coil_tier_2').displayName('Electrum Coil').noValidSpawns(true)
    event.create('coil_tier_3').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/coil_tier_3').displayName('Astralite Coil').noValidSpawns(true)
    event.create('heat_resistant_glass').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/heat_resistant_glass').noValidSpawns(true).defaultCutout()
    event.create('frame_tier_1').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/frame_tier_1').defaultCutout().displayName('Frame Mark I').noValidSpawns(true)
    event.create('frame_tier_2').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/frame_tier_2').defaultCutout().displayName('Frame Mark II').noValidSpawns(true)
    event.create('frame_tier_3').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/frame_tier_3').defaultCutout().displayName('Frame Mark III').noValidSpawns(true)
    event.create('multiblock_tier_1').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/multiblock_tier_1').displayName('Multiblock Mark I').noValidSpawns(true)
    event.create('multiblock_tier_2').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/multiblock_tier_2').displayName('Multiblock Mark II').noValidSpawns(true)
    event.create('multiblock_tier_3').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/multiblock_tier_3').displayName('Multiblock Mark III').noValidSpawns(true)
    event.create('electrical_machine_casing').tagBlock('minecraft:mineable/pickaxe').textureAll('kubejs:block/electrical_machine_casing').noValidSpawns(true)
    event.create('steel_bore_head').tagBlock('minecraft:mineable/pickaxe').noValidSpawns(true)
    kubejs_ore('milothium')
    kubejs_ore('catericite')
    kubejs_ore('darthium')
    kubejs_ore('ecolinit')
})