// priority: 0

StartupEvents.registry('item', event => {
    
    event.create('rough_data_card_substrate').texture('kubejs:item/rough_data_card_substrate')
    event.create('polished_data_card_substrate').texture('kubejs:item/polished_data_card_substrate')
    event.create('data_card_connector').texture('kubejs:item/data_card_connector')
    event.create('blank_data_card').texture('kubejs:item/blank_data_card')
    event.create('mob_simulation_data').texture('kubejs:item/mob_simulation_data')
    
    event.create('nutrient_pulp').texture('kubejs:item/nutrient_pulp')
    event.create('nutrient_bar').food(food => {
        food
        .hunger(8)
        .saturation(16)
        .alwaysEdible()
        .fastToEat()
    }).texture('kubejs:item/nutrient_bar')
    event.create('cake_amalgamation').food(food => {
        food
        .hunger(12)
        .saturation(24)
        .alwaysEdible()
    }).texture('kubejs:item/cake_amalgamation')
    event.create('crystal_inferium').texture('kubejs:item/crystal_inferium').displayName('Inferium Crystal')
    event.create('crystal_prudentium').texture('kubejs:item/crystal_prudentium').displayName('Prudentium Crystal')
    event.create('crystal_tertium').texture('kubejs:item/crystal_tertium').displayName('Tertium Crystal')
    event.create('crystal_soulless_imperium').texture('kubejs:item/crystal_soulless_imperium').displayName('Soulless Imperium Crystal')
    event.create('crystal_imperium').texture('kubejs:item/crystal_imperium').displayName('Imperium Crystal')
    event.create('crystal_supremium').texture('kubejs:item/crystal_supremium').displayName('Supremium Crystal')
    event.create('crystal_insanium').texture('kubejs:item/crystal_insanium').displayName('Insanium Crystal')
    event.create('solid_supremium').texture('kubejs:item/solid_supremium')
    event.create('trace_element_supremium').texture('kubejs:item/trace_element_supremium').displayName('Supremium Trace Element')
    event.create('material_testing_kit').texture('kubejs:item/material_testing_kit')
    event.create('advanced_material_data_card').texture('kubejs:item/advanced_material_data_card')
    event.create('bloody_data_card').texture('kubejs:item/bloody_data_card')
    event.create('compressed_data_card').texture('kubejs:item/compressed_data_card')
    event.create('culinary_data_card').texture('kubejs:item/culinary_data_card')
    event.create('electricity_data_card').texture('kubejs:item/electricity_data_card')
    event.create('twilight_data_card').texture('kubejs:item/twilight_data_card')
    event.create('storage_data_card').texture('kubejs:item/storage_data_card')
    event.create('astral_data_card').texture('kubejs:item/astral_data_card')
    event.create('gem_data_card').texture('kubejs:item/gem_data_card')
    event.create('nuclear_data_card').texture('kubejs:item/nuclear_data_card')
    event.create('emc_data_card').texture('kubejs:item/emc_data_card')
    event.create('inert_infinity_token').texture('kubejs:item/inert_infinity_token')
    event.create('infinity_token').texture('kubejs:item/infinity_token')
    event.create('gateitem_tier1').texture('')
    event.create('gateitem_tier2').texture('')
    event.create('gateitem_tier3').texture('')
    event.create('gateitem_tier4').texture('')
    event.create('gateitem_tier5').texture('')
    event.create('gateitem_tier6').texture('')
    event.create('gateitem_tier7').texture('')
    event.create('gateitem_tier8').texture('')
    event.create('gateitem_tier9').texture('')
    event.create('crushed_iron').texture('')
    event.create('crushed_gold').texture('')
    event.create('crushed_tin').texture('')
    event.create('crushed_copper').texture('')
    event.create('crushed_lead').texture('')
    event.create('crushed_titan').texture('')
    event.create('crushed_mangan').texture('')
    event.create('crushed_cobalt').texture('')
    event.create('crushed_zinc').texture('')
    event.create('crushed_bauxite').texture('')
    event.create('crushed_silver').texture('')
    event.create('dust_blue').texture('kubejs:item/dust_blue')
    event.create('dust_blueish').texture('kubejs:item/dust_blueish')
    event.create('dust_galvanized').texture('kubejs:item/dust_galvanized')
    event.create('dust_orangeish').texture('kubejs:item/dust_orangeish')
    event.create('dust_pale_green').texture('kubejs:item/dust_pale_green')
    event.create('dust_pale_yellow').texture('kubejs:item/dust_pale_yellow')
    event.create('dust_red').texture('kubejs:item/dust_red')
    event.create('dust_redish').texture('kubejs:item/dust_redish')
    event.create('dust_soilent').texture('kubejs:item/dust_soilent')
    event.create('dust_turquoise').texture('kubejs:item/dust_turquoise')
    event.create('dust_yellow').texture('kubejs:item/dust_yellow')
    event.create('ingot_blue').texture('kubejs:item/ingot_blue')
    event.create('ingot_blueish').texture('kubejs:item/ingot_blueish')
    event.create('ingot_galvanized').texture('kubejs:item/ingot_galvanized')
    event.create('ingot_orangeish').texture('kubejs:item/ingot_orangeish')
    event.create('ingot_pale_green').texture('kubejs:item/ingot_pale_green')
    event.create('ingot_pale_yellow').texture('kubejs:item/ingot_pale_yellow')
    event.create('ingot_red').texture('kubejs:item/ingot_red')
    event.create('ingot_redish').texture('kubejs:item/ingot_redish')
    event.create('ingot_soilent').texture('kubejs:item/ingot_soilent')
    event.create('ingot_turquoise').texture('kubejs:item/ingot_turquoise')
    event.create('ingot_yellow').texture('kubejs:item/ingot_yellow')
    event.create('plate_blue').texture('kubejs:item/plate_blue')
    event.create('plate_blueish').texture('kubejs:item/plate_blueish')
    event.create('plate_galvanized').texture('kubejs:item/plate_galvanized')
    event.create('plate_orangeish').texture('kubejs:item/plate_orangeish')
    event.create('plate_pale_green').texture('kubejs:item/plate_pale_green')
    event.create('plate_pale_yellow').texture('kubejs:item/plate_pale_yellow')
    event.create('plate_red').texture('kubejs:item/plate_red')
    event.create('plate_redish').texture('kubejs:item/plate_redish')
    event.create('plate_soilent').texture('kubejs:item/plate_soilent')
    event.create('plate_turquoise').texture('kubejs:item/plate_turquoise')
    event.create('plate_yellow').texture('kubejs:item/plate_yellow')
    event.create('rod_blueish').texture('kubejs:item/rod_blueish')
    event.create('rod_yellow').texture('kubejs:item/rod_yellow')
    event.create('wood_splinter').texture('kubejs:item/wood_splinter')
    event.create('rotor').texture('kubejs:item/rotor')
    event.create('stator').texture('kubejs:item/stator')
    event.create('electric_motor').texture('kubejs:item/electric_motor')
    event.create('raw_catericite').texture('raw_catericite')
    event.create('raw_darthium').texture('raw_darthium')
    event.create('raw_milothium').texture('raw_milothium')
})