ClientEvents.lang('en_us', event => {
    event.add('block.mbd2.kinetic_crusher', 'Kinetic Crusher')
    event.add('block.mbd2.blast_furnace', 'Blast Furnace')
    event.add('block.mbd2.kinetic_crusher_block', 'Kinetic Crushing Wheel')
    event.add('block.mbd2.washing_facility', 'Washing Facility')
    event.add('block.mbd2.item_input_tier_1', 'Item Input Mark I')
    event.add('block.mbd2.item_input_tier_2', 'Item Input Mark II')
    event.add('block.mbd2.item_input_tier_3', 'Item Input Mark III')
    event.add('block.mbd2.item_output_tier_1', 'Item Output Mark I')
    event.add('block.mbd2.item_output_tier_2', 'Item Output Mark II')
    event.add('block.mbd2.item_output_tier_3', 'Item Output Mark III')
    event.add('block.mbd2.fluid_input_tier_2', 'Fluid Input Mark II')
    event.add('block.mbd2.fluid_input_tier_3', 'Fluid Input Mark III')
    event.add('block.mbd2.fluid_input_tier_2', 'Fluid Output Mark II')
    event.add('block.mbd2.energy_input_tier_2', 'Energy Input Mark II')
    event.add('block.mbd2.energy_input_tier_3', 'Energy Input Mark III')
    event.add('block.mbd2.multiplex_hatch_mark_1', 'Multiplex Hatch Mark I')
    event.add('block.mbd2.multiplex_hatch_mark_2', 'Multiplex Hatch Mark II')
    event.add('block.mbd2.multiplex_hatch_mark_3', 'Multiplex Hatch Mark III')
    event.add('block.mbd2.matter_replicator', 'Matter Replicator')
    event.add('block.mbd2.magnetizer', 'Magnetizer')
    event.add('block.mbd2.drill_mk_i', 'Deep Drill')
    event.add('block.mbd2.assembler', 'Assembler')
    event.add('block.mbd2.crystal_chamber', 'Crystal Chamber')
    event.add('block.mbd2.crystal_cutter', 'Crystal Cutter')
    event.add('block.mbd2.model_computer', 'Model Computation Facility')
    event.add('block.mbd2.gods_forge', 'Forge of the Infinity')
    event.add('block.mbd2.mana_input_hatch', 'Mana Input Hatch')
    event.add('block.mbd2.infuser', 'Infuser')
    event.add('block.mbd2.egg_incubator', 'Egg Incubator')
    event.renameItem('industrialforegoing:plastic', 'Bio-Plastic')
    event.renameItem('kubejs:relic_level_up', 'Spacefarers\' Boon')

})

