ClientEvents.lang('en_us', event => {
    event.add('block.mbd2.kinetic_crusher', 'Kinetic Crusher')
    event.add('block.mbd2.blast_furnace', 'Blast Furnace')
    event.add('block.mbd2.kinetic_crusher_block', 'Kinetic Crushing Wheel')
    event.add('block.mbd2.washing_facility', 'Washing Facility')
    event.add('block.mbd2.item_input_tier_1', 'Item Input Tier 1')
    event.add('block.mbd2.item_input_tier_2', 'Item Input Tier 2')
    event.add('block.mbd2.item_input_tier_3', 'Item Input Tier 3')
    event.add('block.mbd2.item_output_tier_1', 'Item Output Tier 1')
    event.add('block.mbd2.item_output_tier_2', 'Item Output Tier 2')
    event.add('block.mbd2.item_output_tier_3', 'Item Output Tier 3')
    event.add('block.mbd2.fluid_input_tier_2', 'Fluid Input Tier 2')
    event.add('block.mbd2.fluid_input_tier_3', 'Fluid Input Tier 3')
    event.add('block.mbd2.energy_input_tier_2', 'Energy Input Tier 2')
    event.add('block.mbd2.energy_input_tier_3', 'Energy Input Tier 3')
    event.add('block.mbd2.cobblestone_generator_tier1', 'Stone Generator')
    event.add('block.mbd2.drill_mk_i', 'Deep Drill')
    event.add('block.mbd2.assembler', 'Assembler')
    event.add('block.mbd2.crystal_chamber', 'Crystal Chamber')
    event.add('block.mbd2.model_computer', 'Model Computation Facility')
    event.renameItem('industrialforegoing:plastic', 'Bio-Plastic')

})

